In [12]:
!git clone https://github.com/Harindhar10/DeepRetro.git

fatal: destination path 'DeepRetro' already exists and is not an empty directory.

In [13]:
!pip install -q rdkit

^C

In [ ]:
# load up USPTO-50k test dataset
import pandas as pd

df = pd.read_csv("/root/workspace/DFS/DeepRetro/data/uspto_50k_test_250.csv")
df.head()

,input,output,reaction_type,cluster_id
0,CS(=O)c1cccc(-c2nc(C=O)ccc2OCCO[Si](C)(C)C(C)(...,CC(C)(C)[Si](C)(C)OCCOc1ccc(C=O)nc1Br.CS(=O)c1...,3,0
1,CC(C)=CCSc1ccc(Br)cc1,CC(C)=CCBr.Sc1ccc(Br)cc1,1,0
2,CCC1(c2ccc(C=O)s2)OCCO1,CCC1(c2cccs2)OCCO1.CN(C)C=O,3,0
3,O=C1Nc2ccccc2C1c1cc(Br)ccc1O,O=C1Nc2ccccc2C1(O)c1cc(Br)ccc1O,9,0
4,CCCCCCCCCCCCCCCCOCC(CN)CC#N,CCCCCCCCCCCCCCCCOCC(CC#N)CN=[N+]=[N-],9,0

# One-step retrosynthesis evaluation of a causal LM

Set `MODEL_ID` in the config cell below to any HuggingFace causal LM; everything downstream
(prompting, generation, checkpoint paths, scoring) is derived from it.

Scored with the same protocol as `DeepRetro/notebooks/prod_challenge.ipynb` (cells 31-39):
canonicalize predicted precursors and ground-truth reactants with RDKit, then require equal
cardinality plus set membership.

- `all_correct` — every predicted precursor is in the ground truth, and the counts match.
- `any_correct` — at least one predicted precursor is in the ground truth, and the counts match.

Reported at **top-1** (first proposal only, directly comparable to prod_challenge, which scores
only `steps[0]`) and at **top-k** (a hit in any of the 3-5 proposals the model returns).

In [ ]:
import ast
import json
import os
import re
import sys

import pandas as pd
import torch
from rdkit import Chem, RDLogger
from tqdm.auto import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer

RDLogger.DisableLog("rdApp.*")  # silence the parse errors we already handle

REPO = "/root/workspace/DFS/DeepRetro"
sys.path.insert(0, REPO)

# Reuse DeepRetro's own prompts. SYS/USER_PROMPT_OPENAI are the non-CoT pair the repo
# uses for models that do not emit <cot> tags -- the right family for instruct models
# like Olmo-3-Instruct. src/variables.py is pure string constants, so this import pulls
# in no litellm/langfuse.
from src.variables import SYS_PROMPT_OPENAI, USER_PROMPT_OPENAI

# --- the only knob that has to change to evaluate a different model ---
MODEL_ID = "allenai/Olmo-3-7B-Instruct"

DATA_CSV = f"{REPO}/data/uspto_50k_test_250.csv"

# Output paths are derived from MODEL_ID so two models never share a checkpoint file.
# run_generation() resumes from RAW_JSONL, so a shared path would make a new model
# silently inherit the previous model's completions.
MODEL_SLUG = MODEL_ID.rstrip("/").split("/")[-1]
DATA_SLUG = os.path.splitext(os.path.basename(DATA_CSV))[0]
OUT_DIR = f"{REPO}/results/{DATA_SLUG}_{MODEL_SLUG}"
RAW_JSONL = f"{OUT_DIR}/raw_generations.jsonl"
RESULTS_CSV = f"{OUT_DIR}/results.csv"
os.makedirs(OUT_DIR, exist_ok=True)
print("writing to", OUT_DIR)

df_eval = pd.read_csv(DATA_CSV, )  # index_col=0
print(df_eval.shape, df_eval.columns.tolist())
df_eval.head()

writing to /root/workspace/DFS/DeepRetro/results/uspto_50k_test_250_Olmo-3-7B-Instruct
(250, 4) ['input', 'output', 'reaction_type', 'cluster_id']

,input,output,reaction_type,cluster_id
0,CS(=O)c1cccc(-c2nc(C=O)ccc2OCCO[Si](C)(C)C(C)(...,CC(C)(C)[Si](C)(C)OCCOc1ccc(C=O)nc1Br.CS(=O)c1...,3,0
1,CC(C)=CCSc1ccc(Br)cc1,CC(C)=CCBr.Sc1ccc(Br)cc1,1,0
2,CCC1(c2ccc(C=O)s2)OCCO1,CCC1(c2cccs2)OCCO1.CN(C)C=O,3,0
3,O=C1Nc2ccccc2C1c1cc(Br)ccc1O,O=C1Nc2ccccc2C1(O)c1cc(Br)ccc1O,9,0
4,CCCCCCCCCCCCCCCCOCC(CN)CC#N,CCCCCCCCCCCCCCCCOCC(CC#N)CN=[N+]=[N-],9,0

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"  # required for correct batched generation


DTYPE = torch.bfloat16
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    dtype=DTYPE,  # transformers>=5 spelling; torch_dtype is deprecated
    device_map="auto",
    low_cpu_mem_usage=True,
)
model.eval()
print(MODEL_ID, "->", model.dtype, getattr(model, "hf_device_map", model.device))


def build_prompt(molecule: str) -> str:
    """Render the chat prompt exactly as src/utils/llm.py::call_LLM builds its messages.

    Note: .replace() rather than .format() -- USER_PROMPT_OPENAI embeds a literal JSON
    schema with { } braces, so .format() would raise.

    Base models ship no chat template, so fall back to a plain system+user concatenation
    rather than crashing.
    """
    user = USER_PROMPT_OPENAI.replace("{target_smiles}", molecule)
    if getattr(tokenizer, "chat_template", None):
        messages = [
            {"role": "system", "content": SYS_PROMPT_OPENAI},
            {"role": "user", "content": user},
        ]
        return tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
    return f"{SYS_PROMPT_OPENAI}\n\n{user}\n\n"


print(build_prompt(df_eval.iloc[0]["input"])[:1200])

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/581 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

/venv/main/lib/python3.12/site-packages/torchao/quantization/quant_api.py:1825: SyntaxWarning: invalid escape sequence '\.'
  * regex for parameter names, must start with `re:`, e.g. `re:language\.layers\..+\.q_proj.weight`.

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/4.64G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

Cancellation requested; stopping current tasks.

KeyboardInterrupt:

In [ ]:
# Ports of src/utils/llm.py::split_json_openAI and ::validate_split_json.
# Inlined rather than imported: src.utils.llm pulls in litellm/langfuse, which are not
# installed here. Two robustness additions over the originals, because a 7B model drops
# the <json> tags and emits real JSON far more often than Claude/o1 do:
#   - json.loads first, ast.literal_eval as fallback (the repo uses only the latter)
#   - regex fallback to a bare {...} block when the tags are missing

_BARE_JSON = re.compile(r"\{.*\"data\".*\}", re.DOTALL)


def split_json_content(res_text: str):
    """Return (status, json_content). 200 on success, 502 on failure."""
    start = res_text.find("<json>")
    end = res_text.find("</json>")
    if start != -1 and end != -1 and end > start:
        content = res_text[start + len("<json>"):end].strip()
        if content:
            return 200, content
    m = _BARE_JSON.search(res_text)  # tags missing -- salvage the object itself
    if m:
        return 200, m.group(0).strip()
    return 502, ""


def loads_lenient(json_content: str):
    try:
        return json.loads(json_content)
    except Exception:
        return ast.literal_eval(json_content)  # Python-literal style (repo behaviour)


def validate_split_json(json_content: str):
    """Return (status, molecules, explanations, confidence_scores). 504 on failure."""
    try:
        result = loads_lenient(json_content)
        return 200, result["data"], result["explanation"], result["confidence_scores"]
    except Exception:
        return 504, [], [], []


def parse_response(res_text: str):
    """Full response -> (status, proposals). proposals is a list of precursor-SMILES lists."""
    status, json_content = split_json_content(res_text)
    if status != 200:
        return status, []
    status, molecules, _expl, _conf = validate_split_json(json_content)
    if status != 200:
        return status, []
    # Normalise: a single flat list of strings means one proposal, not many.
    if molecules and all(isinstance(m, str) for m in molecules):
        molecules = [molecules]
    proposals = [
        [s for s in prop if isinstance(s, str) and s.strip()]
        for prop in molecules
        if isinstance(prop, list)
    ]
    proposals = [p for p in proposals if p]
    return (200, proposals) if proposals else (504, [])

In [ ]:
MAX_NEW_TOKENS = 1024
BATCH_SIZE = 4  # set to 1 if the two T4s run out of memory


@torch.inference_mode()
def generate_batch(molecules):
    """Greedy-decode one batch; returns the completions with the prompt stripped."""
    prompts = [build_prompt(m) for m in molecules]
    # add_special_tokens=False: chat templates already emit BOS themselves.
    enc = tokenizer(prompts, return_tensors="pt", padding=True, add_special_tokens=False)
    enc = {k: v.to(model.device) for k, v in enc.items()}
    out = model.generate(
        **enc,
        max_new_tokens=MAX_NEW_TOKENS,
        do_sample=False,  # greedy, matching the repo's temperature=0.0
        pad_token_id=tokenizer.pad_token_id,
    )
    gen = out[:, enc["input_ids"].shape[1]:]
    return tokenizer.batch_decode(gen, skip_special_tokens=True)


def load_checkpoint(path):
    done = {}
    if os.path.exists(path):
        with open(path) as f:
            for line in f:
                line = line.strip()
                if line:
                    rec = json.loads(line)
                    done[rec["mol_no"]] = rec
    return done


def run_generation(df, limit=None):
    """Generate completions for df, appending to RAW_JSONL and skipping finished rows."""
    done = load_checkpoint(RAW_JSONL)
    todo = [(i, row) for i, row in df.iterrows() if int(i) not in done]
    if limit is not None:
        todo = todo[:limit]
    print(f"{len(done)} already done, generating {len(todo)}")

    with open(RAW_JSONL, "a") as fout:
        for start in tqdm(range(0, len(todo), BATCH_SIZE)):
            chunk = todo[start:start + BATCH_SIZE]
            try:
                texts = generate_batch([row["input"] for _, row in chunk])
            except Exception as e:
                print(f"generation failed for {[int(i) for i, _ in chunk]}: {e}")
                texts = [""] * len(chunk)
            for (i, row), text in zip(chunk, texts):
                fout.write(json.dumps({
                    "mol_no": int(i),
                    "model_id": MODEL_ID,
                    "input": row["input"],
                    "output": row["output"],
                    "raw": text,
                }) + "\n")
            fout.flush()  # checkpoint survives a kernel restart mid-run


# Smoke test: one molecule end to end before committing to all 500.
_smoke = generate_batch([df_eval.iloc[0]["input"]])[0]
print(_smoke[:2000])
print("\n--- parsed ---")
print(parse_response(_smoke))

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

<json>
{
  "data": [
    ["C1=CC=CC=C1C(=O)N(C)C1=CC=CC=C1C(=O)C1=CC=CC=C1C(C)(C)C(C)(C)C", "C(=O)N(C)(C)C1=CC=CC=C1C(=O)C1CC(OC(=O)O)C1C(=O)C1"],
    ["C1=CC=CC=C1C(=O)C1C(=O)C1C1C(=O)C1C1C(=O)C1C1C1", "C1=CC=CC=C1C(=O)C1C(=O)C1C(=O)C1C(=O)C1"],
    ["C1=CC=CC=C1C(=O)C1C(=O)C1C1C(=O)C1C(=O)C1", "C1=CC=CC=C1C(=O)C1C(=O)C1C1C(=O)C1"],
    ["C1=CC=CC=C1C(=O)C1C(=O)C1", "C1=CC=CC=C1C(=O)C1C(=O)C1 (deprotonation step, likely from an enol form)"]
  ],
  "explanation": [
    "The first precursor represents a nitrile (NC) that could undergo a Curtius rearrangement with an acyl chloride (C(=O)Cl) to form the observed amide functionality.",
    "The second precursor is a diacyl chloride (C(=O)C1(C=O)C1) that could react with an alcohol (C1=CC=CC=C1C(=O)C1) via nucleophilic acyl substitution to form an ester linkage.",
    "The third precursor is a β-keto ester (C1=CC=CC=C1C(=O)OC1) that could be reduced to the target amide using a reducing agent such as LiAlH4 under appropriate conditions.",
    "The fourth precursor is a simple amide (C1=CC=CC=C1C(=O)N(C)C1) that could be acylated with an acid chloride to generate the extended amide chain (though this is less likely in one step, it is included for completeness).",
    "The fifth proposal is a less direct possibility: a cyclic ketene (C1=C=C=O) reacting with an alcohol to form an acetal/ester intermediate, which could then undergo further rearrangement or condensation to yield the target (low confidence)."
  ],
  "confidence_scores": [0.85, 0.75, 0.65, 0.55, 0.40]
}
</json>

--- parsed ---
(200, [['C1=CC=CC=C1C(=O)N(C)C1=CC=CC=C1C(=O)C1=CC=CC=C1C(C)(C)C(C)(C)C', 'C(=O)N(C)(C)C1=CC=CC=C1C(=O)C1CC(OC(=O)O)C1C(=O)C1'], ['C1=CC=CC=C1C(=O)C1C(=O)C1C1C(=O)C1C1C(=O)C1C1C1', 'C1=CC=CC=C1C(=O)C1C(=O)C1C(=O)C1C(=O)C1'], ['C1=CC=CC=C1C(=O)C1C(=O)C1C1C(=O)C1C(=O)C1', 'C1=CC=CC=C1C(=O)C1C(=O)C1C1C(=O)C1'], ['C1=CC=CC=C1C(=O)C1C(=O)C1', 'C1=CC=CC=C1C(=O)C1C(=O)C1 (deprotonation step, likely from an enol form)']])

In [ ]:
# Dry run on the first 10 rows first. Re-running this cell should say "10 already done,
# generating 0" -- that confirms the checkpoint works before the long run.
run_generation(df_eval, limit=10)

0 already done, generating 10

  0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
# Full run over all 250 molecules. Hours on 2x T4 -- resumable, so it is safe to
# interrupt and re-run this cell.
run_generation(df_eval)

In [ ]:
# The prod_challenge.ipynb metric (cell 38), factored so top-1 and top-k share it.
# One deviation from the original: CanonSmiles is wrapped in try/except. prod_challenge
# lets it throw because AiZynthFinder only ever emitted valid SMILES; an LLM will not, and
# an invalid proposal has to score 0 rather than abort the loop.


def canon(smiles: str):
    try:
        return Chem.CanonSmiles(smiles)
    except Exception:
        return None


def score_proposal(pred_smiles_list, gt_canon):
    """Return (any_correct, all_correct, not_common, missed, valid)."""
    pred = [canon(s) for s in pred_smiles_list]
    if any(p is None for p in pred):
        return 0, 0, [s for s, p in zip(pred_smiles_list, pred) if p is None], gt_canon, False
    same_len = len(gt_canon) == len(pred)
    any_c = int(any(p in gt_canon for p in pred) and same_len)
    all_c = int(all(p in gt_canon for p in pred) and same_len)
    not_common = [p for p in pred if p not in gt_canon]
    missed = [g for g in gt_canon if g not in pred]
    return any_c, all_c, not_common, missed, True


def score_record(rec):
    """Score one generation record at top-1 and top-k."""
    gt_canon = [canon(s) for s in str(rec["output"]).split(".")]
    gt_canon = [g for g in gt_canon if g is not None]

    status, proposals = parse_response(rec["raw"])
    row = {
        "mol_no": rec["mol_no"],
        "input": rec["input"],
        "output": rec["output"],
        "parse_status": status,
        "n_proposals": len(proposals),
        "proposals": proposals,
        "any_correct": 0,
        "all_correct": 0,
        "any_correct_topk": 0,
        "all_correct_topk": 0,
        "first_hit_rank": None,
        "not_common": [],
        "missed": gt_canon,
        "has_invalid_smiles": 0,
    }
    if status != 200 or not proposals:
        return row  # parse failure counts as incorrect, it is not dropped

    any_invalid = False
    for rank, prop in enumerate(proposals, start=1):
        any_c, all_c, not_common, missed, valid = score_proposal(prop, gt_canon)
        if not valid:
            any_invalid = True
        if rank == 1:  # top-1: exactly what prod_challenge scores
            row.update(any_correct=any_c, all_correct=all_c,
                       not_common=not_common, missed=missed)
        row["any_correct_topk"] = max(row["any_correct_topk"], any_c)
        if all_c and row["first_hit_rank"] is None:
            row["first_hit_rank"] = rank
        row["all_correct_topk"] = max(row["all_correct_topk"], all_c)
    row["has_invalid_smiles"] = int(any_invalid)
    return row


# Sanity check: the ground truth must score (1, 1) against itself on every row.
_gt_ok = all(
    score_proposal([s for s in str(r["output"]).split(".")],
                   [canon(s) for s in str(r["output"]).split(".")])[:2] == (1, 1)
    for _, r in df_eval.iterrows()
)
print("ground truth scores perfectly against itself:", _gt_ok)

In [ ]:
records = load_checkpoint(RAW_JSONL)
df_results = pd.DataFrame([score_record(rec) for rec in records.values()])
df_results = df_results.set_index("mol_no").sort_index()
df_results.to_csv(RESULTS_CSV)

n = len(df_results)
print(f"model: {MODEL_ID}")
print(f"Scored {n} / {len(df_eval)} molecules from {RAW_JSONL}\n")

# prod_challenge cell 39 wording, so the numbers sit side by side with the DeepRetro run.
print("=== top-1 (first proposal -- prod_challenge protocol) ===")
print("All correct %", 100 * df_results.all_correct.sum() / n)
print("Any correct %", 100 * df_results.any_correct.sum() / n)

print("\n=== top-k (best of the 3-5 proposals) ===")
print("All correct %", 100 * df_results.all_correct_topk.sum() / n)
print("Any correct %", 100 * df_results.any_correct_topk.sum() / n)

print("\n=== top-n curve (all_correct) ===")
for k in (1, 3, 5):
    hits = df_results.first_hit_rank.dropna().le(k).sum()
    print(f"top-{k}: {100 * hits / n:.2f}%")

print("\n=== response quality ===")
print(f"parse failures  : {100 * (df_results.parse_status != 200).sum() / n:.2f}%")
print(f"invalid SMILES  : {100 * df_results.has_invalid_smiles.sum() / n:.2f}%")
print(f"mean proposals  : {df_results.n_proposals.mean():.2f}")
print(f"\nDenominator is all {n} scored rows -- parse failures count as incorrect. "
      "prod_challenge dropna()'d its pipeline failures (cell 36), so its numbers are "
      "computed over a smaller, easier set.")

df_results.head(10)

In [18]:
!python Claude_GPT_eval/moleculenet_cost_anthropic.py

=== claude-sonnet-5-5 | K=10 | shots=fixed | splits=('valid', 'test') | seeds=1 ===
dataset             split       K   reqs  prompt tok out tok cache     cost $  no-cache $
-----------------------------------------------------------------------------------------
bace_classification valid      10    151       1,191     512   yes       0.48        0.57
bace_classification test       10    152       1,191     512   yes       0.48        0.57
bace_regression     valid      10    151       1,221     513   yes       0.48        0.57
bace_regression     test       10    152       1,221     513   yes       0.48        0.58
bbbp                valid      10    203       1,091     512   yes       0.63        0.74
bbbp                test       10    189       1,071     512   yes       0.58        0.69
clearance           valid      10     84       1,101     513   yes       0.26        0.31
clearance           test       10     84       1,101     513   yes       0.26        0.31
clintox             valid      10    142       1,230     527   yes       0.46        0.55
clintox             test       10    143       1,210     527   yes       0.46        0.55
delaney             valid      10    113         781     513   yes       0.33        0.38
delaney             test       10    113         781     513   yes       0.33        0.38
freesolv            valid      10     64         671     513   yes       0.19        0.21
freesolv            test       10     65         671     513   yes       0.19        0.21
hiv                 valid      10  4,103         971     512   yes      12.42       14.49
hiv                 test       10  4,102         961     512   yes      12.37       14.44
lipo                valid      10    419       1,101     513   yes       1.30        1.54
lipo                test       10    420       1,101     513   yes       1.30        1.54
sider               valid      10    133       4,476     883   yes       0.86        1.18
sider               test       10    127       4,496     883   yes       0.83        1.13
tox21               valid      10    774       1,960     637   yes       3.17        3.98
tox21               test       10    762       1,960     637   yes       3.12        3.92
-----------------------------------------------------------------------------------------
TOTAL (runnable)                  12,646      15.0M   6.77M            40.96       48.82

=== claude-sonnet-5-5 | K=all | shots=fixed | splits=('valid', 'test') | seeds=1 ===
WARNING: [claude-sonnet-5-5 | hiv/valid] K=32840 -> 1,807,133 tokens exceeds the 1,000,000-token context window. Largest K that fits: 18,164.
WARNING: [claude-sonnet-5-5 | hiv/test] K=32840 -> 1,807,123 tokens exceeds the 1,000,000-token context window. Largest K that fits: 18,165.
dataset             split       K   reqs  prompt tok out tok cache     cost $  no-cache $
-----------------------------------------------------------------------------------------
bace_classification valid   1,210    151      91,191     512   yes       6.60       14.16
bace_classification test    1,210    152      91,191     512   yes       6.64       14.25
bace_regression     valid   1,210    151      94,821     513   yes       6.84       14.71
bace_regression     test    1,210    152      94,821     513   yes       6.89       14.80
bbbp                valid   1,640    203     107,041     512   yes      10.26       22.25
bbbp                test    1,640    189     107,021     512   yes       9.56       20.71
clearance           valid     668     84      45,845     513   yes       1.98        4.07
clearance           test      668     84      45,845     513   yes       1.98        4.07
clintox             valid   1,163    142      91,164     527   yes       6.22       13.32
clintox             test    1,163    143      91,144     527   yes       6.26       13.41
delaney             valid     902    113      34,677     513   yes       2.07        4.21
delaney             test      902    113      34,677     513   yes       2.07        4.21
freesolv            valid     513     64      14,755     513   yes       0.60        1.11
freesolv            test      513     65      14,755     513   yes       0.61        1.13
hiv                 valid  32,840  4,103   1,806,621     512   yes               TOO LONG
hiv                 test   32,840  4,102   1,806,611     512   yes               TOO LONG
lipo                valid   3,359    419     228,833     513   yes      43.64       96.96
lipo                test    3,359    420     228,833     513   yes      43.74       97.19
sider               valid   1,106    133     425,340     883   yes      26.15       57.16
sider               test    1,106    127     425,360     883   yes      25.00       54.58
tox21               valid   6,248    774     925,184     637   yes     319.02      718.56
tox21               test    6,248    762     925,184     637   yes     314.10      707.42
-----------------------------------------------------------------------------------------
TOTAL (runnable)                   4,441    1865.4M   2.57M           840.22     1878.24
Excluded (exceeds context window): hiv/test, hiv/valid

=== Total cost (USD), shots=fixed, splits=('valid', 'test'), seeds=1 ===
     K    claude-fable-5-1     claude-opus-5-5   claude-sonnet-5-5    claude-haiku-5-5
     0              196.04               78.42               39.21                0.38
     1              198.04               79.26               39.63                0.40
     5              193.49               77.77               38.88                0.38
    10              203.40               81.93               40.96                0.50
    50              284.16              115.75               57.87                1.42
   100              385.10              158.03               79.01                2.57
   500            1,192.63              496.26              248.13               16.81
   all           4,015.01*           1,680.44*             840.22*             216.05*
* some datasets exceed the context window at this K and are excluded from the total

In [ ]:
import pandas as pd
import moleculenet_cost as mc

total_chars, total_tokens = 0, 0
for name in mc.DATASETS:
    df = pd.read_csv(f"data/{name}/train.csv")
    sample = df["smiles"].sample(min(300, len(df)), random_state=0).tolist()
    cpt = mc.calibrate_chars_per_token(sample)
    chars = len("\n".join(sample))
    total_chars += chars
    total_tokens += chars / cpt
    print(f"{name:<20} {cpt:.2f}")

mc.CHARS_PER_TOKEN = total_chars / total_tokens   # pooled across all datasets
print("pooled:", round(mc.CHARS_PER_TOKEN, 2))

In [ ]:
import pandas as pd
import moleculenet_cost as mc

df = pd.read_csv("data/hiv/train.csv")              # path to one of your split files
sample = df["smiles"].sample(500, random_state=0).tolist()   # change "smiles" if your column is named differently

cpt = mc.calibrate_chars_per_token(sample, model="claude-sonnet-5-5")
print(f"{cpt:.2f} chars per token")

mc.CHARS_PER_TOKEN = cpt    # override the 2.0 default
mc.report()                 # estimates now use the measured value
mc.sweep()

ModuleNotFoundError: No module named 'moleculenet_cost'

In [8]:
!python Claude_GPT_eval/cost.py

bace_classification  1.01
bace_regression      1.01
bbbp                 1.02
clearance            1.02
clintox              1.03
delaney              1.00
freesolv             0.99
hiv                  1.02
lipo                 1.01
sider                1.02
tox21                1.02
pooled: 1.01

In [5]:
import os

In [19]:
!python Claude_GPT_eval/moleculenet_cost_openai.py

=== gpt-6.1-sol | K=10 | shots=fixed | splits=('valid', 'test') | seeds=1 ===
dataset             split       K   reqs  prompt tok out tok cache long     cost $  no-cache $
----------------------------------------------------------------------------------------------
bace_classification valid      10    151       1,191     512   yes            0.45        0.57
bace_classification test       10    152       1,191     512   yes            0.45        0.57
bace_regression     valid      10    151       1,221     513   yes            0.45        0.57
bace_regression     test       10    152       1,221     513   yes            0.45        0.58
bbbp                valid      10    203       1,091     512    no            0.74        0.74
bbbp                test       10    189       1,071     512    no            0.69        0.69
clearance           valid      10     84       1,101     513   yes            0.25        0.31
clearance           test       10     84       1,101     513   yes            0.25        0.31
clintox             valid      10    142       1,230     527   yes            0.43        0.55
clintox             test       10    143       1,210     527   yes            0.44        0.55
delaney             valid      10    113         781     513    no            0.38        0.38
delaney             test       10    113         781     513    no            0.38        0.38
freesolv            valid      10     64         671     513    no            0.21        0.21
freesolv            test       10     65         671     513    no            0.21        0.21
hiv                 valid      10  4,103         971     512    no           14.49       14.49
hiv                 test       10  4,102         961     512    no           14.44       14.44
lipo                valid      10    419       1,101     513   yes            1.23        1.54
lipo                test       10    420       1,101     513   yes            1.23        1.54
sider               valid      10    133       4,476     883   yes            0.77        1.18
sider               test       10    127       4,496     883   yes            0.74        1.13
tox21               valid      10    774       1,960     637   yes            2.95        3.98
tox21               test       10    762       1,960     637   yes            2.90        3.92
----------------------------------------------------------------------------------------------
TOTAL (runnable)                  12,646      15.0M   6.77M                 44.52       48.82

=== gpt-6.1-sol | K=all | shots=fixed | splits=('valid', 'test') | seeds=1 ===
WARNING: [gpt-6.1-sol | hiv/valid] K=32840 -> 1,807,133 tokens exceeds the 1,050,000-token context window. Largest K that fits: 19,073.
WARNING: [gpt-6.1-sol | hiv/test] K=32840 -> 1,807,123 tokens exceeds the 1,050,000-token context window. Largest K that fits: 19,074.
dataset             split       K   reqs  prompt tok out tok cache long     cost $  no-cache $
----------------------------------------------------------------------------------------------
bace_classification valid   1,210    151      91,191     512   yes            4.48       14.16
bace_classification test    1,210    152      91,191     512   yes            4.51       14.25
bace_regression     valid   1,210    151      94,821     513   yes            4.64       14.71
bace_regression     test    1,210    152      94,821     513   yes            4.67       14.80
bbbp                valid   1,640    203     107,041     512   yes            6.94       22.25
bbbp                test    1,640    189     107,021     512   yes            6.46       20.71
clearance           valid     668     84      45,845     513   yes            1.38        4.07
clearance           test      668     84      45,845     513   yes            1.38        4.07
clintox             valid   1,163    142      91,164     527   yes            4.22       13.32
clintox             test    1,163    143      91,144     527   yes            4.25       13.41
delaney             valid     902    113      34,677     513   yes            1.46        4.21
delaney             test      902    113      34,677     513   yes            1.46        4.21
freesolv            valid     513     64      14,755     513   yes            0.45        1.11
freesolv            test      513     65      14,755     513   yes            0.46        1.13
hiv                 valid  32,840  4,103   1,806,621     512   yes  yes               TOO LONG
hiv                 test   32,840  4,102   1,806,611     512   yes  yes               TOO LONG
lipo                valid   3,359    419     228,833     513   yes           29.12       96.96
lipo                test    3,359    420     228,833     513   yes           29.19       97.19
sider               valid   1,106    133     425,340     883   yes  yes      34.52      114.02
sider               test    1,106    127     425,360     883   yes  yes      33.01      108.88
tox21               valid   6,248    774     925,184     637   yes  yes     420.88     1435.88
tox21               test    6,248    762     925,184     637   yes  yes     414.39     1413.62
----------------------------------------------------------------------------------------------
TOTAL (runnable)                   4,441    1865.4M   2.57M               1007.88     3412.94
Excluded (exceeds context window): hiv/test, hiv/valid

=== Total cost (USD), shots=fixed, splits=('valid', 'test'), seeds=1 ===
     K     gpt-6-astra     gpt-6.1-sol      gpt-6-luna
     0          196.45           39.29            0.38
     1          201.22           40.24            0.43
     5          212.24           42.35            0.54
    10          223.83           44.52            0.66
    50          260.26           49.97            1.02
   100          339.40           63.89            1.81
   500          972.49          175.30            8.14
   all       5,717.36*       1,007.88*          56.51*
* some datasets exceed the context window at this K and are excluded from the total

In [16]:
!python Claude_GPT_eval/claude_smoketest.py --datasets bbbp

Built 2 requests across 1 dataset(s).
Submitted batch msgbatch_01ALn3ucn2J377JqLx5yG194 with 2 requests.
  in_progress: 0 ok, 0 errored, 2 processing
  in_progress: 0 ok, 0 errored, 2 processing
  in_progress: 0 ok, 0 errored, 2 processing
  in_progress: 0 ok, 0 errored, 2 processing
  in_progress: 0 ok, 0 errored, 2 processing
  in_progress: 0 ok, 0 errored, 2 processing
  in_progress: 0 ok, 0 errored, 2 processing
  in_progress: 0 ok, 0 errored, 2 processing
  in_progress: 0 ok, 0 errored, 2 processing
  ended: 2 ok, 0 errored, 0 processing
Saved per-request results to pilot_results/msgbatch_01ALn3ucn2J377JqLx5yG194.csv

2/2 requests succeeded.

dataset                n  think med    p95    max  truncated  parse ok  cache hit
bbbp                   2          2      2      2          0      100%        50%

Thinking tokens per request: median 2, p95 2, max 2
Truncated by max_tokens:     0 of 2
Answers parsed:              100%
Cache hit rate:              50% (requests with a cacheable prefix)
Pilot cost:                  $0.01

For moleculenet_cost.py:
  MODEL_CONFIG["claude-sonnet-5-5"]["thinking_tokens"] = 2   # median
  CACHE_HIT_RATE = 0.50
  Suggested MAX_TOKENS for the full run: ~503

In [15]:
!python Claude_GPT_eval/claude_smoketest.py --datasets bbbp --dry-run

Built 2 requests across 1 dataset(s).

--- example system prompt ---
You are an expert medicinal chemist predicting molecular properties from SMILES.

Task: Blood-brain barrier penetration.
Targets: p_np

For each target, give the probability (0 to 1) that the molecule is positive. Use two decimal places.

Respond with a single JSON object and nothing else, using exactly these keys: ["p_np"]

Labelled examples (null = label not measured):
SMILES: C1=C(Cl)C=CC3=C1N(C2=C(C=CC=C2)S3)CCCN5CCN(CCOC(C4=CC(=C(OC)C(=C4)OC)OC)=O)CC5
Answer: {"p_np": 1}
SMILES: C3=C(N2C1=C([NH]N=C1N(C(=O)CC2=O)C)C)C=CC=C3
Answer: {"p_np": 1}
SMILES: CCC(=O)O[C@@](Cc1ccccc1)([C@H](C)CN(C)C)c2ccccc2
Answer: {"p_np": 1}
SMILES: CC(CCc1ccccc1)NCC(O)c2ccc(O)c(c2)C(N)=O
Answer: {"p_np": 0}
SMILES: N1(c2c(CCc3c1cccc3)cccc2)CCCN
Answer: {"p_np": 1}
SMILES: CC4CN(CCCn2c1ccccc1c3ccccc23)CC(C)N4
Answer: {"p_np": 1}
SMILES: c1cc2c(C(N[C@@H](CC)c3ccccc3)=O)c(c(nc2cc1)c1ccccc1)OCC(O)=O
Answer: {"p_np": 0}
SMILES: [C@H]23C1=C(C=C(C(CCCCCC)(C)C)C=C1O)OC([C@@H]2CCC(C3)=O)(C)C
Answer: {"p_np": 1}
SMILES: C1=C(Cl)C=CC3=C1\C(C2=C(C=CC=C2)S3)=C\C4C5CCN(C4)CC5
Answer: {"p_np": 1}
SMILES: C1=CC=CC2=C1N(C(=O)N2)CCCN4CCC(C(C3=CC=C(F)C=C3)=O)CC4
Answer: {"p_np": 1}
--- example user message ---
SMILES: C3=C(C1N2C(=NC1)NCC2)C=CC=C3

Prompt tokens per dataset (first request):
  bbbp                    859